### ISSUE TITLE
java.lang.NoSuchMethodError: No virtual method keySet()

### ISSUE THREAD

**Issue by damirmiljkovic** [UnboundID/ldapsdk#21]
I have followed instructions for building and installing UnboundID Android app, copied unboundid-ldapsdk-se.jar from .../package/unboundid-ldapsdk-3.2.1-se into lib folder but  when I add server ID, IP address and hit Test Settings button I get this exception and application rashes:

va.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Ljava/util/concurrent/ConcurrentHashMap; or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
                                                       at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1092)
                                                       at com.unboundid.ldap.sdk.LDAPConnectionReader.close(LDAPConnectionReader.java:1056)
                                                       at com.unboundid.ldap.sdk.LDAPConnectionInternals.close(LDAPConnectionInternals.java:617)
                                                       at com.unboundid.ldap.sdk.LDAPConnection.setClosed(LDAPConnection.java:4433)
                                                       at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1089)
                                                       at com.unboundid.ldap.sdk.LDAPConnectionReader.run(LDAPConnectionReader.java:417)

**Comment by dirmgr** [comment]
This exception indicates that you compiled the LDAP SDK with a version of Java that is newer than the one that Android supports. I think that Android is based on Java SE 6, so you should try compiling the LDAP SDK jar file using that version of Java. Or you could take the jar file from one of the official releases, which should be built with an appropriate version.

**Comment by damirmiljkovic** [comment]
I downloaded LDAP SDK from this link (https://docs.ldap.com/ldap-sdk/files/unboundid-ldapsdk-3.2.0-se.zip) but now I am getting this exception:
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet
                                                                 at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1092)
                                                                 at com.unboundid.ldap.sdk.LDAPConnectionReader.close(LDAPConnectionReader.java:1056)
                                                                 at com.unboundid.ldap.sdk.LDAPConnectionInternals.close(LDAPConnectionInternals.java:617)
                                                                 at com.unboundid.ldap.sdk.LDAPConnection.setClosed(LDAPConnection.java:4433)
                                                                 at com.unboundid.ldap.sdk.LDAPConnectionReader.closeInternal(LDAPConnectionReader.java:1089)
                                                                 at com.unboundid.ldap.sdk.LDAPConnectionReader.run(LDAPConnectionReader.java:444)

**Comment by dirmgr** [comment]
This still indicates that there's some kind of mismatch between the java versions being used to compile and run the LDAP SDK and the Android app. I don't really understand exactly why you're seeing this particular exception, since the java.util.concurrent.ConcurrentHashMap.keySet method has been available since Java SE 5, although its return type did change between Java SE 7 and 8 (and that explains the stack trace you originally posted).

Ensuring that everything (the LDAP SDK and the Android app) is compiled with the same Java version that's going to be used to run the app should resolve the problem.

The most surefire way to avoid it would be to get rid of the LDAP SDK jar file and just include the LDAP SDK source directly in your own codebase, but that would be complicated a bit by the fact that some of the LDAP SDK's source code is dynamically generated by the LDAP SDK build process. You could probably work around that by building the LDAP SDK and then taking all of the source files from the src and gen-src/messages directory. But then you'd also need to ensure that when you package your app, the messages/unboundid-ldapsdk*.properties files are included in the class root, and that the resource/standard-schema.ldif file is in the com/unboundid/ldap/sdk/schema directory. Since this is so complicated and potentially fragile, I'd definitely recommend this as a last resort, or just to verify that you can get it working with the LDAP SDK built as part of your app before figuring out how to include it separately.

**Comment by damirmiljkovic** [comment]
Thank you very much for help, I had to adjust my environment and it is working now.
